mappings = {
    "Aruba": "ABW",
    "Afghanistan": "AFG",
    "Angola": "AGO",
    "Anguilla": "AIA",
    "Åland Islands": "ALA",
    "Albania": "ALB",
    "Andorra": "AND",
    "Netherlands Antilles": "ANT",
    "United Arab Emirates": "ARE",
    "Argentina": "ARG",
    "Armenia": "ARM",
    "American Samoa": "ASM",
    "Antigua and Barbuda": "ATG",
    "Australia": "AUS",
    "Austria": "AUT",
    "Azerbaijan": "AZE",
    "Burundi": "BDI",
    "Belgium": "BEL",
    "Benin": "BEN",
    "Bonaire, Saint Eustatius and Saba": "BES",
    "Bonaire, Sint Eustatius and Saba": "BES",
    "Burkina Faso": "BFA",
    "Bangladesh": "BGD",
    "Bulgaria": "BGR",
    "Bahrain": "BHR",
    "Bahamas": "BHS",
    "Bosnia and Herzegovina": "BIH",
    "Belarus": "BLR",
    "Belize": "BLZ",
    "Bermuda": "BMU",
    "Bolivia": "BOL",
    "Bolivia (Plurinational State of)": "BOL",
    "Brazil": "BRA",
    "Barbados": "BRB",
    "Brunei Darussalam": "BRN",
    "Bhutan": "BTN",
    "Botswana": "BWA",
    "Central African Republic": "CAF",
    "Canada": "CAN",
    "Switzerland": "CHE",
    "Chile": "CHL",
    "China": "CHN",
    "Côte d'Ivoire": "CIV",
    "Cameroon": "CMR",
    "Democratic Republic of the Congo": "COD",
    "Congo, Democratic Republic of the": "COD",
    "Congo": "COG",
    "Cook Islands": "COK",
    "Colombia": "COL",
    "Comoros": "COM",
    "Cape Verde": "CPV",
    "Cabo Verde": "CPV",
    "Costa Rica": "CRI",
    "Cuba": "CUB",
    "Curaçao": "CUW",
    "Cyprus": "CYP",
    "Czechia": "CZE",
    "Czech Republic": "CZE",
    "Germany": "DEU",
    "Djibouti": "DJI",
    "Dominica": "DMA",
    "Denmark": "DNK",
    "Dominican Republic": "DOM",
    "Algeria": "DZA",
    "Ecuador": "ECU",
    "Egypt": "EGY",
    "Eritrea": "ERI",
    "Western Sahara": "ESH",
    "Spain": "ESP",
    "Estonia": "EST",
    "Ethiopia": "ETH",
    "Finland": "FIN",
    "Fiji": "FJI",
    "Falkland Islands (Malvinas)": "FLK",
    "France": "FRA",
    "Faeroe Islands": "FRO",
    "Faroe Islands": "FRO",
    "Micronesia (Federated States of)": "FSM",
    "Gabon": "GAB",
    "United Kingdom": "GBR",
    "United Kingdom of Great Britain and Northern Ireland": "GBR",
    "Georgia": "GEO",
    "Guernsey": "GGY",
    "Ghana": "GHA",
    "Guinea": "GIN",
    "Guadeloupe": "GLP",
    "Gambia": "GMB",
    "Guinea-Bissau": "GNB",
    "Equatorial Guinea": "GNQ",
    "Greece": "GRC",
    "Grenada": "GRD",
    "Greenland": "GRL",
    "Guatemala": "GTM",
    "French Guiana": "GUF",
    "Guyana": "GUY",
    "Hong Kong": "HKG",
    "Honduras": "HND",
    "Croatia": "HRV",
    "Haiti": "HTI",
    "Hungary": "HUN",
    "Indonesia": "IDN",
    "Isle of Man": "IMN",
    "India": "IND",
    "Ireland": "IRL",
    "Iran": "IRN",
    "Iran (Islamic Republic of)": "IRN",
    "Iraq": "IRQ",
    "Iceland": "ISL",
    "Israel": "ISR",
    "Italy": "ITA",
    "Jamaica": "JAM",
    "Jersey": "JEY",
    "Jordan": "JOR",
    "Japan": "JPN",
    "Kazakhstan": "KAZ",
    "Kenya": "KEN",
    "Kyrgyzstan": "KGZ",
    "Cambodia": "KHM",
    "Kiribati": "KIR",
    "Saint Kitts and Nevis": "KNA",
    "South Korea": "KOR",
    "Korea, Republic of": "KOR",
    "Kosovo": "XKX",
    "Kuwait": "KWT",
    "Laos": "LAO",
    "Lao People's Democratic Republic": "LAO",
    "Lebanon": "LBN",
    "Liberia": "LBR",
    "Libya": "LBY",
    "Saint Lucia": "LCA",
    "Liechtenstein": "LIE",
    "Sri Lanka": "LKA",
    "Lesotho": "LSO",
    "Lithuania": "LTU",
    "Luxembourg": "LUX",
    "Latvia": "LVA",
    "Macao": "MAC",
    "Saint Martin (French part)": "MAF",
    "Morocco": "MAR",
    "Monaco": "MCO",
    "Moldova": "MDA",
    "Moldova, Republic of": "MDA",
    "Madagascar": "MDG",
    "Maldives": "MDV",
    "Mexico": "MEX",
    "Marshall Islands": "MHL",
    "North Macedonia": "MKD",
    "Macedonia (Republic of)": "MKD",
    "Mali": "MLI",
    "Malta": "MLT",
    "Myanmar": "MMR",
    "Montenegro": "MNE",
    "Mongolia": "MNG",
    "Mozambique": "MOZ",
    "Mauritania": "MRT",
    "Montserrat": "MSR",
    "Martinique": "MTQ",
    "Mauritius": "MUS",
    "Malawi": "MWI",
    "Malaysia": "MYS",
    "Mayotte": "MYT",
    "Namibia": "NAM",
    "New Caledonia": "NCL",
    "Niger": "NER",
    "Nigeria": "NGA",
    "Nicaragua": "NIC",
    "Niue": "NIU",
    "Netherlands": "NLD",
    "Norway": "NOR",
    "Nepal": "NPL",
    "Nauru": "NRU",
    "New Zealand": "NZL",
    "Oman": "OMN",
    "Pakistan": "PAK",
    "Panama": "PAN",
    "Peru": "PER",
    "Philippines": "PHL",
    "Palau": "PLW",
    "Papua New Guinea": "PNG",
    "Poland": "POL",
    "Puerto Rico": "PRI",
    "North Korea": "PRK",
    "Korea (Democratic People's Republic of)": "PRK",
    "Portugal": "PRT",
    "Paraguay": "PRY",
    "Occupied Palestinian Territory": "PSE",
    "State of Palestine": "PSE",
    "Palestine, State of": "PSE",
    "French Polynesia": "PYF",
    "Qatar": "QAT",
    "Réunion": "REU",
    "Romania": "ROU",
    "Russia": "RUS",
    "Russian Federation": "RUS",
    "Rwanda": "RWA",
    "Saudi Arabia": "SAU",
    "Sudan": "SDN",
    "Senegal": "SEN",
    "Singapore": "SGP",
    "Saint Helena": "SHN",
    "Svalbard and Jan Mayen": "SJM",
    "Solomon Islands": "SLB",
    "Sierra Leone": "SLE",
    "El Salvador": "SLV",
    "San Marino": "SMR",
    "Somalia": "SOM",
    "Saint Pierre and Miquelon": "SPM",
    "Serbia": "SRB",
    "South Sudan": "SSD",
    "Sao Tome and Principe": "STP",
    "Suriname": "SUR",
    "Slovakia": "SVK",
    "Slovenia": "SVN",
    "Sweden": "SWE",
    "Eswatini": "SWZ",
    "Swaziland": "SWZ",
    "Sint Maarten (Dutch part)": "SXM",
    "Seychelles": "SYC",
    "Syria": "SYR",
    "Syrian Arab Republic": "SYR",
    "Turks and Caicos Islands": "TCA",
    "Chad": "TCD",
    "Togo": "TGO",
    "Thailand": "THA",
    "Tajikistan": "TJK",
    "Turkmenistan": "TKM",
    "Timor-Leste": "TLS",
    "Tonga": "TON",
    "World": "TOTAL",
    "Global": "TOTAL",
    "Trinidad and Tobago": "TTO",
    "Tunisia": "TUN",
    "Turkey": "TUR",
    "Türkiye": "TUR",
    "Tuvalu": "TUV",
    "Taiwan": "TWN",
    "Taiwan, Province of China": "TWN",
    "Tanzania": "TZA",
    "Tanzania, United Republic of": "TZA",
    "Uganda": "UGA",
    "Ukraine": "UKR",
    "Uruguay": "URY",
    "USA": "USA",
    "United States of America": "USA",
    "Uzbekistan": "UZB",
    "Vatican City": "VAT",
    "Saint Vincent and the Grenadines": "VCT",
    "Venezuela": "VEN",
    "Venezuela (Bolivarian Republic of)": "VEN",
    "British Virgin Islands": "VGB",
    "Virgin Islands (British)": "VGB",
    "Virgin Islands (U.S.)": "VIR",
    "Viet Nam": "VNM",
    "Vanuatu": "VUT",
    "Wallis and Futuna Islands": "WLF",
    "Samoa": "WSM",
    "International Aviation": "XIA",
    "International Shipping": "XIS",
    "Yemen": "YEM",
    "South Africa": "ZAF",
    "Zambia": "ZMB",
    "Zimbabwe": "ZWE",
}
